Hello, I am  2
Hello, I am  1
Hello, I am  0
data sent to node 1
data received on node 1 from node 0
Range
[range(0, 677), range(677, 1354)]
data sent to node 2
data received on node 2 from node 0
requested_nodes_list
[[], [], []]
tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]]) torch.Size([1354, 1433])
tensor([[   0,    0,    0,  ..., 2057, 2057, 2056],
        [   1,  472,  473,  ...,  136, 1131,  463]]) torch.Size([2, 7544])
world size 3
request nodes: 0
request nodes: 0
Traceback (most recent call last):
  File "GCN_Cora_Distributed_MulNode.py", line 185, in <module>
    main(rank, world_size, host_addr_full)
  File "GCN_Cora_Distributed_MulNode.py", line 171, in main
    _, pred = model(data).max(dim=1)
  File "/home/dsys2352/miniconda3/envs/dist_GNN/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "GCN_Cora_Distributed_MulNode.py", line 136, in forward
    x = self.conv1(x, edge_index)
  File "/home/dsys2352/miniconda3/envs/dist_GNN/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "GCN_Cora_Distributed_MulNode.py", line 19, in forward
    return self.propagate(edge_index, size=(x.size(0), x.size(0)), x=x)
  File "/home/dsys2352/miniconda3/envs/dist_GNN/lib/python3.6/site-packages/torch_geometric/nn/conv/message_passing.py", line 310, in propagate
    size, kwargs)
  File "/home/dsys2352/miniconda3/envs/dist_GNN/lib/python3.6/site-packages/torch_geometric/nn/conv/message_passing.py", line 202, in __collect__
    j if arg[-2:] == '_j' else i)
  File "/home/dsys2352/miniconda3/envs/dist_GNN/lib/python3.6/site-packages/torch_geometric/nn/conv/message_passing.py", line 171, in __lift__
    return src.index_select(self.node_dim, index)
IndexError: index out of range in self
Range
[range(0, 677), range(677, 1354)]
requested_nodes_list
[[], [1, 2, 3, 4, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 22, 23, 24, 25, 27, 28, 29, 31, 33, 34, 36, 38, 39, 40, 42, 44, 46, 47, 48, 49, 50, 53, 54, 55, 56, 57, 59, 60, 61, 62, 63, 65, 66, 67, 68, 69, 71, 72, 74, 76, 77, 79, 80, 81, 82, 83, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 102, 104, 105, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 120, 124, 125, 126, 129, 130, 131, 135, 136, 140, 141, 143, 144, 145, 148, 152, 153, 154, 156, 157, 162, 165, 166, 167, 168, 169, 170, 171, 174, 175, 176, 177, 178, 179, 182, 183, 184, 187, 188, 189, 190, 191, 192, 193, 195, 196, 197, 198, 199, 200, 201, 204, 205, 207, 209, 211, 213, 214, 215, 216, 217, 219, 221, 225, 226, 227, 229, 231, 232, 233, 234, 237, 238, 239, 241, 242, 243, 247, 248, 249, 250, 251, 252, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 267, 268, 269, 271, 272, 273, 274, 276, 277, 278, 279, 280, 281, 282, 284, 285, 286, 287, 289, 290, 291, 292, 295, 296, 297, 303, 304, 306, 308, 309, 310, 311, 312, 314, 315, 316, 317, 319, 320, 321, 322, 323, 325, 326, 327, 328, 330, 331, 332, 333, 334, 336, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 356, 357, 358, 360, 362, 363, 365, 366, 367, 368, 369, 370, 371, 372, 375, 376, 377, 378, 379, 380, 381, 382, 386, 387, 388, 390, 391, 392, 393, 394, 397, 399, 400, 402, 405, 407, 409, 411, 412, 413, 414, 415, 416, 417, 418, 419, 420, 421, 422, 424, 425, 426, 427, 428, 430, 432, 433, 435, 436, 438, 439, 441, 442, 443, 445, 446, 448, 449, 450, 452, 453, 454, 458, 459, 460, 461, 462, 463, 464, 465, 466, 470, 471, 474, 475, 476, 477, 478, 480, 481, 482, 485, 486, 488, 489, 491, 493, 494, 497, 498, 499, 500, 503, 505, 506, 507, 509, 510, 511, 512, 513, 514, 515, 516, 518, 519, 520, 521, 522, 524, 525, 526, 527, 528, 529, 530, 532, 533, 534, 535, 536, 537, 538, 539, 540, 542, 545, 547, 554, 555, 556, 558, 563, 564, 565, 567, 570, 571, 573, 575, 577, 578, 581, 582, 583, 584, 585, 586, 589, 590, 591, 593, 594, 595, 596, 597, 598, 599, 600, 601, 602, 603, 604, 605, 606, 607, 608, 609, 610, 611, 612, 614, 615, 617, 618, 620, 621, 623, 624, 625, 626, 628, 629, 630, 631, 638, 640, 642, 643, 644, 645, 647, 648, 649, 651, 652, 653, 654, 656, 657, 660, 662, 663, 665, 668, 670, 671, 672, 675, 676], [677, 678, 679, 680, 681, 683, 684, 689, 690, 691, 692, 693, 694, 695, 696, 697, 698, 700, 702, 703, 707, 710, 711, 712, 715, 718, 719, 720, 721, 722, 724, 727, 728, 729, 730, 732, 733, 735, 736, 737, 739, 740, 742, 743, 744, 746, 748, 749, 750, 753, 754, 755, 756, 757, 758, 759, 760, 761, 762, 763, 765, 767, 768, 771, 772, 773, 775, 777, 778, 779, 780, 781, 783, 784, 785, 787, 788, 789, 790, 791, 793, 794, 795, 797, 798, 799, 801, 802, 803, 804, 806, 807, 808, 809, 810, 811, 815, 816, 817, 818, 819, 820, 821, 822, 823, 825, 826, 827, 830, 831, 832, 834, 836, 839, 840, 841, 844, 848, 849, 850, 852, 853, 854, 855, 856, 859, 860, 861, 862, 864, 866, 868, 869, 872, 873, 874, 875, 877, 878, 885, 886, 887, 889, 891, 892, 894, 895, 898, 899, 900, 902, 903, 904, 906, 908, 909, 910, 912, 915, 916, 917, 919, 920, 923, 924, 925, 926, 927, 928, 929, 930, 933, 935, 936, 938, 939, 943, 944, 946, 947, 949, 953, 955, 956, 958, 960, 961, 962, 963, 964, 965, 966, 967, 968, 969, 970, 971, 972, 973, 974, 976, 977, 979, 980, 983, 984, 986, 988, 990, 991, 992, 994, 997, 998, 1000, 1003, 1004, 1005, 1006, 1007, 1009, 1012, 1014, 1015, 1016, 1018, 1019, 1020, 1023, 1025, 1026, 1027, 1028, 1029, 1030, 1032, 1033, 1034, 1035, 1036, 1037, 1038, 1039, 1040, 1044, 1045, 1046, 1049, 1050, 1051, 1052, 1054, 1055, 1056, 1059, 1060, 1061, 1063, 1070, 1071, 1073, 1074, 1075, 1077, 1079, 1081, 1082, 1083, 1085, 1086, 1087, 1088, 1090, 1091, 1092, 1097, 1098, 1099, 1100, 1101, 1102, 1103, 1105, 1107, 1109, 1110, 1111, 1114, 1117, 1118, 1119, 1120, 1121, 1122, 1124, 1125, 1126, 1127, 1128, 1130, 1131, 1133, 1134, 1135, 1137, 1138, 1139, 1140, 1141, 1142, 1144, 1145, 1146, 1147, 1148, 1149, 1154, 1156, 1157, 1158, 1160, 1162, 1164, 1165, 1166, 1167, 1168, 1169, 1171, 1172, 1173, 1174, 1175, 1177, 1178, 1180, 1181, 1183, 1185, 1188, 1189, 1190, 1191, 1194, 1195, 1197, 1198, 1199, 1200, 1205, 1207, 1208, 1210, 1211, 1212, 1214, 1216, 1217, 1222, 1225, 1226, 1228, 1229, 1230, 1231, 1233, 1234, 1235, 1236, 1239, 1241, 1243, 1244, 1245, 1246, 1248, 1249, 1250, 1251, 1252, 1253, 1254, 1255, 1256, 1258, 1260, 1262, 1264, 1265, 1266, 1267, 1268, 1269, 1270, 1271, 1272, 1274, 1275, 1278, 1279, 1280, 1283, 1286, 1287, 1288, 1290, 1296, 1298, 1299, 1300, 1301, 1302, 1303, 1305, 1309, 1311, 1316, 1317, 1318, 1320, 1324, 1327, 1329, 1331, 1335, 1336, 1337, 1339, 1340, 1342, 1345, 1349, 1350, 1352, 1353]]
tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 1.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]]) torch.Size([1354, 1433])
tensor([[1354, 1354, 1354,  ..., 2055, 2055, 2055],
        [1529, 1821, 2014,  ..., 1518, 1746, 2054]]) torch.Size([2, 6576])
world size 3
request nodes: 477
Traceback (most recent call last):
  File "GCN_Cora_Distributed_MulNode.py", line 185, in <module>
    main(rank, world_size, host_addr_full)
  File "GCN_Cora_Distributed_MulNode.py", line 171, in main
    _, pred = model(data).max(dim=1)
  File "/home/dsys2352/miniconda3/envs/dist_GNN/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "GCN_Cora_Distributed_MulNode.py", line 116, in forward
    requested_nodes_list = recv_object(src = 1)
  File "/home/dsys2352/DSassignment/GCN/utils.py", line 284, in recv_object
    dist.recv(size, src=src)
  File "/home/dsys2352/miniconda3/envs/dist_GNN/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 850, in recv
    pg.recv([tensor], src, tag).wait()
RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:575] Connection closed by peer [10.141.0.2]:38832
Traceback (most recent call last):
  File "/home/dsys2352/miniconda3/envs/dist_GNN/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/dsys2352/miniconda3/envs/dist_GNN/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/dsys2352/miniconda3/envs/dist_GNN/lib/python3.6/site-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/home/dsys2352/miniconda3/envs/dist_GNN/lib/python3.6/site-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/home/dsys2352/miniconda3/envs/dist_GNN/lib/python3.6/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/dsys2352/miniconda3/envs/dist_GNN/bin/python', '-u', 'GCN_Cora_Distributed_MulNode.py']' returned non-zero exit status 1.
Killing subprocess 1096323
srun: error: node002: task 1: Exited with exit code 1
Traceback (most recent call last):
  File "/home/dsys2352/miniconda3/envs/dist_GNN/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/dsys2352/miniconda3/envs/dist_GNN/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/dsys2352/miniconda3/envs/dist_GNN/lib/python3.6/site-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/home/dsys2352/miniconda3/envs/dist_GNN/lib/python3.6/site-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/home/dsys2352/miniconda3/envs/dist_GNN/lib/python3.6/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/dsys2352/miniconda3/envs/dist_GNN/bin/python', '-u', 'GCN_Cora_Distributed_MulNode.py']' returned non-zero exit status 1.
Killing subprocess 290710
srun: error: node024: task 2: Exited with exit code 1
